version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678" # for DEBUG=debugpy
      - "5555:5555" # for DEBUG=web-pdb
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DEBUG # can be empty, debugpy, or pdb
    depends_on:
      - db
      - redis
      - prometheus  # Add Prometheus as a dependency
    restart: always

  db:
    image: "postgres:15.2"
    env_file:
      - ./.env
    restart: always
    ports:
      - "9432:5432"
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
      - /tmp/postgresql/data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: "prom/prometheus:v2.30.3"  # Use a specific version
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
