version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DEBUG
    depends_on:
      - db
      - redis
      - prometheus
    restart: always

  db:
    image: "postgres:15.2"
    env_file:
      - ./.env
    restart: always
    ports:
      - "9432:5432"
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
      - /tmp/postgresql/data:/var/lib/postgresql/data

  test_db:
    image: "postgres:15.2"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: "prom/prometheus:v2.30.3"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always
