global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['0.0.0.0:8000']
      
  - job_name: 'fastapi_metrics'
    static_configs:
      - targets: ['server:8001'] 